#Updated dynamically from UI
#Mon Mar 23 23:03:24 IST 2026
Authentication_Type=OAUTH
Authorization=Basic c2ItQUdSUFJfR1JWLVNvZGFsZXMtZGV2ISB0MzQzMDo5OGM3ZGVjZS0zYWExLTQwYTgtYjkxMi1mMzVhMTNjMGQ5YjMkNmVtYkttSFI5d2dVdGV1WUh4SXlIaFZhNWFIeUktV25qYzBjajhHV1psRT0\=
CLIENT_ID=sb-AGRPR_GRV-Sodales-dev\! t3430
CLIENT_SECRET=98c7dece-3aa1-40a8-b912-f35a13c0d9b3$6embKmHR9wgUteuYHxIyHhVa5aHyI-Wnjc0cj8GWZlE\=
GRANT_TYPE=client_credentials
TOKEN_URL=https\://scq-internal-qa-agrpr-5mvnLrdu.authentication.ca10.hana.ondemand.com/oauth/token
